flowise-embed/src/utils/fileClassificationUtils.ts
Refatoracoes nos checklists baseadas nos feedbacks.
=> [ACI - 38] - Testes do checklist

flowise-embed/src/utils/fileClassificationUtils.ts
=> [AA - 213] - refactor: standardizes checklists

flowise-embed/src/constants.ts, flowise-embed/src/utils/parallelApiExecutor.ts
[N8N](https://n8n.startse.com/workflow/Se8vVwKtulslPaZ4)
=> [ACI-35] - Analise critica - Etapa 7 - ICMS Importação

flowise-embed/src/constants.ts, flowise-embed/src/utils/parallelApiExecutor.ts
[N8N](https://n8n.startse.com/workflow/TmCimayAPlfqfLxe)
=> [ACI-34]- Analise critica - Etapa 6 - Atributos da NCM

flowise-embed/src/constants.ts, flowise-embed/src/utils/parallelApiExecutor.ts
- Adicionado URL para realizar Etapa 2
=> [ACI-30] - Analise critica - Etapa 2 - Tratamento tributário

flowise-embed/src/constants.ts, flowise-embed/src/utils/parallelApiExecutor.ts
[N8N](https://n8n.startse.com/workflow/3a2AqiMZ5deb0vFW)
=> [ACI - 31] Analise critica - Etapa 3 - Defesa comercial

flowise-embed/src/components/Bot.tsx, flowise-embed/src/utils/complianceUtils.ts, flowise-embed/src/utils/fileClassificationUtils.ts, flowise-embed/src/utils/jsonUtils.ts
Em síntese, foram modificados pontos dos checklists que retornaram do feedback. Porém, foi modificado o funcionamento do compliance especifico do conhecimento BL com o CE mercante, para que o importador do ce mercante seja comparado ao consignatário do BL.
=> [ACI - 51] - Feat/adjust cross validation

compliance.html, critical_analysis.html, flowise-embed/src/assets/index.css, flowise-embed/src/assets/menu.css, flowise-embed/src/components/Bot.tsx, flowise-embed/src/components/icons/MenuIcon.tsx, flowise-embed/src/constants.ts, flowise-embed/src/features/menu/components/Menu.tsx, flowise-embed/src/features/menu/components/MenuButton.tsx, flowise-embed/src/features/menu/components/MenuItem.tsx, flowise-embed/src/features/menu/index.ts, flowise-embed/src/register.tsx, flowise-embed/src/window.ts, js/data.js
=> [ACI-54]-Criar menu do interseas

flowise-embed/src/components/Bot.tsx
- Adicionado trecho de código para quando não for encontrado assinatura.
=> [ACI-68] - [Compliance] Melhorar a experiência da identificação de assinatura

flowise-embed/src/components/Bot.tsx, flowise-embed/src/service/documentsDBService.ts, flowise-embed/src/utils/pdfUtils.ts
Ao iniciar um novo chat com o assistente, clicando no botão de “novo chat”, salvar o ID do chat recém gerado no banco de dados.
Criar também o relacionamento de documento com chat, uma FK na tabela de documentos.
=> [ACI-18] - ACI-18   Salvar ID do chat no banco de dados

flowise-embed/src/components/Bot.tsx, flowise-embed/src/utils/complianceUtils.ts, flowise-embed/src/utils/messageUtils.ts
Ajuste das mensagens de li e loco
=> [ACI-76] - [Compliance] Ajustar regra de negócio para alerta de LI/LPCO

flowise-embed/src/utils/fileClassificationUtils.ts
=> [ACI-75] - [Compliance] Corrigir padronização de nomenclaturas entre documentos

flowise-embed/src/components/Bot.tsx, flowise-embed/src/utils/messageUtils.ts
=> [ACI-105] - Corrigir fluxo de análise crítica - Correção das mensagens para nova tentativa de descoberta de NCM

flowise-embed/src/utils/compareDocuments.ts
=> [ACI-97] - [Compliance] Considerar documentos com compliance específico ao fazer o compliance geral de outros documentos

flowise-embed/src/utils/complianceUtils.ts, flowise-embed/src/utils/fileClassificationUtils.ts
=> [CI-106] - [Compliance] Mapeamento de dados de containeres em BL e CE

flowise-embed/src/utils/fileClassificationUtils.ts
Modificações relacionadas a extração de valores totais de frete, peso e valores de mercadorias
=> [ACI-70] - [Compliance] Adicionar somatórias de frete e peso às conferências dos documentos

flowise-embed/src/assets/menu.css, flowise-embed/src/features/menu/components/Menu.tsx
=> [ACI-120] - [Menu] Realçar o chat atualmente ativo no menu

flowise-embed/src/components/Bot.tsx, flowise-embed/src/utils/criticalAnalysisUtils.ts, flowise-embed/src/utils/messageUtils.ts
Adaptamos o fluxo de analise crítica do flowise para que sempre retorne a mensagem final das etapas, assim conseguindo salvar o histórico num formato mais amigável do que o caminho paralelo que tínhamos encontrado para os fluxos do N8N. A task toda se baseou em adaptar o front para o fluxo que adaptamos para esse cenário. 
agentflow: https://interseas-flowise.paas.startse.com/agentcanvas/fa473f90-6e94-4b6d-ae6d-089aafbb9a9a
=> refactor: critical analysis iteration request logic

flowise-embed/src/components/Bot.tsx, flowise-embed/src/utils/messageUtils.ts
=> [ACI-123] - [Análise Crítica] Mostrar mensagem de aviso no tratamento administrativo e tributário apenas uma vez, no início do texto

assets/js/auth.js, assets/styles/login.css, index.html
Front-end passando a utilizar o fluxo "auth/v2" do N8N para a autenticação.
O fluxo no N8N passou a utilizar o serviço de auth do Supabase para autenticar, ao invés de usar um esquema simples e estático.
Fluxos do N8N relacionados:
- [Autenticação](https://interseas-n8n.paas.startse.com/workflow/75c4v2s54GaZBuQ9)
- [Validação de sessão](https://interseas-n8n.paas.startse.com/workflow/xFh1vB2TV1VGt5B7)
=> Supabase auth
